
services:
  homer:
    image: b4bz/homer:latest
    container_name: Homer
    ports:
      - 80:8080
    user: 1000:1000 # default
#    user: 0:0 # For when Default doesn't work
    environment:
      - INIT_ASSETS=1 # default
    volumes:
      - ./assets/:/www/assets
      - ./assets/tools:/www/assets/tools
      - ./assets/custom.css:/www/assets/custom.css  
volumes:
  assets:
