
services:
  velociraptor:
    image: wlambert/velociraptor:latest
    container_name: Velociraptor
    hostname: velociraptor
    restart: unless-stopped
    ports:
      - "8600:8000"
      - "8601:8001"
      - "8609:8889"
    volumes:
      - ./velociraptor:/velociraptor/:rw
    environment:
      - VELOX_USER=${VELOX_USER}
      - VELOX_PASSWORD=${VELOX_PASSWORD}
      - VELOX_ROLE=${VELOX_ROLE}
      - VELOX_SERVER_URL=${VELOX_SERVER_URL}
      - VELOX_FRONTEND_HOSTNAME=${VELOX_FRONTEND_HOSTNAME}

# .env
# VELOX_USER=admin
# VELOX_PASSWORD=admin
# VELOX_ROLE=administrator
# VELOX_SERVER_URL=http://10.1.1.16:8609
# VELOX_FRONTEND_HOSTNAME=MedaRaptor
# VELOX_SERVER_URL2=https://raptor.4n6post.com/
