
services:
  Vaultwarden:
    image: vaultwarden/server:latest
    container_name: Hal-VaultWarden
    environment:
      SIGNUPS_ALLOWED: true
      INVITATIONS_ALLOWED: true
      DISABLE_ADMIN_TOKEN: false
      # apt install argon2 echo -n '$2TnXFVf6qgHxG^a#hj8@tex2HTNRXxpWH#6z!w10' | argon2 "$(openssl rand -base64 32)" -e -id -k 
      # 65540 -t 3 -p 4 Escape Output so that all 5 $ have two. eg. $$argon2id~ vs $argon2id~
      ADMIN_TOKEN: $$argon2id$$v=19$$m=65540,t=3,p=4$$MnBIa1JhMDlRQzN2ZVVWNHY3VHlZQkg5YlBLSnVrbFozbjNOQXVGTnFiaz0$$fT918w+4ozfZvdc+fHGJMl4dF1BV03KTcLFEytepLP8
      WEBSOCKET_ENABLED: false
    ports:
      - 9998:80
      - 9999:443
    volumes:
      - ./Vaultwarden/data:/data/
    restart: unless-stopped
  
volumes:
  Vaultwarden: