# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy app.py and requirements.txt to the working directory
COPY app.py requirements.txt /app/

COPY index.html /app/templates/

# Upgrade pip and install Python dependencies
RUN pip install --upgrade pip && \
        pip install --no-cache-dir -r requirements.txt

# Install system dependencies
RUN apt-get update && \
        apt-get install -y --no-install-recommends \
                imagemagick \
                tesseract-ocr \
                tesseract-ocr-eng \
                tesseract-ocr-ukr \
                tesseract-ocr-rus \
                tesseract-ocr-fra && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Expose the necessary ports
EXPOSE 5000
EXPOSE 1006

# Define environment variables
ENV OLLAMA_HOST=0.0.0.0

ENV HOSTIP=localhost

# Run app.py when the container launches
CMD ["python", "app.py"]
